### PR TITLE
fix: do not update changelog if new version exists

### PR DESCRIPTION
**Pull request by MarcoIeni**
Closes https://github.com/MarcoIeni/release-plz/issues/448

### CODE REVIEW

**Comment by brainstorm** [comment]
Hi @MarcoIeni, will this fix the [following amount of PRs being opened and immediately closed](https://github.com/umccr/htsget-rs/pulls?q=is%3Apr+is%3Aclosed+chore+release+)?:

Screenshot 2023-01-17 at 11 29 03 am

It clutters closed PRs log and generates too much noise on Slack :/

/cc @mmalenic

**Comment by MarcoIeni** [comment]
Hi! This change is unrelated. This is the issue you are looking for: https://github.com/MarcoIeni/release-plz/issues/280

It would be great if you can write your thoughts in the comments. 
E.g. Do you like the force push more than the closed PRs? Are you afraid the force push is going to override your changes? 

Anyway, I understand thst like this is noisy. 
I will try to implement pr updates this week :)

**Comment by brainstorm** [comment]
> Have you experienced PRs being open and closed without any activity in the repo?

There was indeed some activity (additional commits), but I'd expect `release-plz` to update the existing unmerged PR without opening and immediately closing a new PR :-S

> on every commit, the pr is being closed and re-opened. I want to change this behavior with https://github.com/MarcoIeni/release-plz/issues/280: I want to update the existing pr.

Precisely! Thanks :)

**Comment by MarcoIeni** [comment]
I started working on this on https://github.com/MarcoIeni/release-plz/pull/470
Sorry if it's not out yet. I hope to get it merged by next week!

**Comment by MarcoIeni** [comment]
I have released the new release-plz version. Please tell me if it's working as expected :)

**Comment by brainstorm** [comment]
I thought the action was updated in unison :-S ... I just merged a PR and it generated a new release: https://github.com/umccr/htsget-rs/pulls

Could you bump the release-plz-action repo?

**Comment by MarcoIeni** [comment]
The new version was picked by the action, but from your [logs](https://github.com/umccr/htsget-rs/actions/runs/4020643569/jobs/6908783777) it seems there's a bug:
image
release-plz used the old mechanism (close + open) as a fallback.
In my tests it worked (you can see force-push [here](https://github.com/MarcoIeni/rust-workspace-example/pull/116)), but I might need to try it in a more complex repo. Sorry about this, I will try to fix it this week.

I know what the problem is by the way, I used `git stash` to save the previous changes, but the changelogs were not committed, so the next `git checkout` didn't work. I will find a better strategy :)

**Comment by MarcoIeni** [comment]
I released a new version of release-plz. Let me know if it works :)

**Comment by brainstorm** [comment]
Thanks @MarcoIeni for your attention and help, it seems like it failed to push the new crates to crates.io when merging the PR though:

https://github.com/umccr/htsget-rs/actions/runs/4050705588/jobs/6968347778

/cc @mmalenic @victorskl

**Comment by MarcoIeni** [comment]
You have a circular dependency.

test depends on search:
https://github.com/umccr/htsget-rs/blob/d8a1f6a9cf321aff2f17fbb54cf61bb4fe3e9151/htsget-test/Cargo.toml#L41


and viceversa:

https://github.com/umccr/htsget-rs/blob/d8a1f6a9cf321aff2f17fbb54cf61bb4fe3e9151/htsget-search/Cargo.toml#L55

The error should be better, but I think this won't work with cargo publish, too

**Comment by MarcoIeni** [comment]
I guess that if you don't want to publish the `test` crate you can drop the version from here:
https://github.com/umccr/htsget-rs/blob/d8a1f6a9cf321aff2f17fbb54cf61bb4fe3e9151/htsget-search/Cargo.toml#L55

and `publish = false` here (see [docs](https://doc.rust-lang.org/cargo/reference/manifest.html#the-publish-field)):
https://github.com/umccr/htsget-rs/blob/d8a1f6a9cf321aff2f17fbb54cf61bb4fe3e9151/htsget-test/Cargo.toml#L11

but I haven't tested it.

**Comment by MarcoIeni** [comment]
Sorry about that. I also encountered this error, too. I just fixed it and released a new version.
Can you try running release-plz again?

**Comment by brainstorm** [comment]
> Sorry about that. I also encountered this error, too. I just fixed it and released a new version. Can you try running release-plz again? I don't know if the github "re-run workflow" button is enough to fix the error. If it doesn't fix it, try triggering the ci by pushing another commit.
> 
> Again, sorry for all these issues. 😅

No worries, sorry to bother you with all of them ;P

I just clicked re-run and this appears to work as expected now: https://github.com/umccr/htsget-rs/actions/runs/4059091910/jobs/6987514723

Yanked htsget-config 0.1.1 on crates.io to keep everything in line for next release, so we'll see on the next PR merge and/or commits :)

**Comment by MarcoIeni** [comment]
> You have a circular dependency.
> 
> test depends on search: https://github.com/umccr/htsget-rs/blob/d8a1f6a9cf321aff2f17fbb54cf61bb4fe3e9151/htsget-test/Cargo.toml#L41
> 
> and viceversa:
> 
> https://github.com/umccr/htsget-rs/blob/d8a1f6a9cf321aff2f17fbb54cf61bb4fe3e9151/htsget-search/Cargo.toml#L55
> 
> The error should be better, but I think this won't work with cargo publish, too

I'm looking back at this error to fix #507.
I learned that you can have circular dependencies if one of the two is a `dev-dependency`. So this answer I gave is wrong.

The problem might be [here](https://github.com/umccr/htsget-rs/blob/d8a1f6a9cf321aff2f17fbb54cf61bb4fe3e9151/htsget-search/Cargo.toml#L14), where you have a feature exporting the `htsget-test` crate. Sorry for the confusion! I hope your design wasn't impacted too much by this wrong analysis :/

**Comment by brainstorm** [comment]
No worries, @mmalenic figured this out in https://github.com/umccr/htsget-rs/pull/161 and fixed it :)

Not semantically ideal to have to be forced to promote a `dev-dependency` to a regular `dependency` to fix this, but we'll live with that.

**Comment by mmalenic** [comment]
Yeah, no worries. I think there's an open [issue](https://github.com/rust-lang/cargo/issues/6915) for enabling features on dev-dependencies, which lead us to the workaround of promoting the dev-dependency to a regular dependency.

**Pull request merged**
