### PR TITLE
chore: enable docker builds for arm

### PR DESCRIPTION
**Pull request by suryapandian**
Tried building `release-plz` in mac m1 arm and it succeeded, so I am guessing linux arm also should succeed

### CODE REVIEW

**Comment by MarcoIeni** [comment]
Hey Surya 👋 
Thanks for checking this out!
Let's test this before merging it!
Right now docker build doesn't run on PRs (to save compute resources). I'm testing your change in https://github.com/MarcoIeni/release-plz/pull/712 :)

**Comment by MarcoIeni** [comment]
Looks like it works 🎉 Thanks Surya! 🙏 
Closes https://github.com/MarcoIeni/release-plz/issues/164

**Comment by suryapandian** [comment]
> Looks like it works 🎉 Thanks Surya! 🙏 Closes #164

Thank you Marco. Planning of working on some of your simple `good-first-issues` in course of time 🤞 
Happy weekend!

**Comment by MarcoIeni** [comment]
Sounds awesome, thanks! Good weekend, you too :)

**Pull request merged**
