### PR TITLE
feat: add check for mandatory fields in all packages

### LINKED ISSUE #1762: release-plz init: check if the mandatory fields of `Cargo.toml` are present
## Motivations

Many people forget to add `license` and `description` to their Cargo.toml.

## Solution

Use the cargo metadata library to check if these fields are present in all non public packages. You can use [this](https://github.com/MarcoIeni/release-plz/blob/c664c887c510766c1964260bb4b633e7ddace625/crates/release_plz_core/src/project.rs#L91) function

If something is missing, fail and report the error.

### PR DESCRIPTION
**Pull request by KekmaTime**
I have introduced a new method `check_mandatory_fields` to the Project struct.
The method verifies the presence of 'license' and 'description' fields in Cargo.toml
for both publishable and non-publishable packages

closes #1762

### CODE REVIEW

**Comment by MarcoIeni** [comment]
Let's just check publishable packages 👍
Non publishable packages don't need those.

Also, can you call this method from the init command?

**Comment by KekmaTime** [comment]
> Let's just check publishable packages 👍 Non publishable packages don't need those.
> 
> Also, can you call this method from the init command?

oh okay ill do that right away. also where is the init command implemented i'm sort of lost there 😓

**Comment by MarcoIeni** [comment]
It's implemented here:

https://github.com/MarcoIeni/release-plz/blob/781ba5d9910c4e18f9f2647c24c1917c526dac77/crates/release_plz/src/init/mod.rs#L10

It's called from main here:

https://github.com/MarcoIeni/release-plz/blob/781ba5d9910c4e18f9f2647c24c1917c526dac77/crates/release_plz/src/main.rs#L71

**Comment by KekmaTime** [comment]
> Hi! Are you still interested in working on this? Or should someone else continue this work?

@MarcoIeni Sorry I was busy with some stuff. ill work on this !

**Comment by MarcoIeni** [comment]
no worries, thanks!

**Review by MarcoIeni — APPROVED** [review]
thanks!

**Pull request merged**
