### PR TITLE
feat(backend): GitLab on-premise support and multilevel URLs, SSH git repos

### PR DESCRIPTION
**Pull request by mbodmer**
- Add support for on-premise hosted GitLab, not only gitlab.com
- Add support for SSH git repositories -> will be converted to "https" API URL
- Add support for multi level gitlab groups
- Respect upper case PRIVATE-TOKEN header
- Mark PRIVATE-TOKEN header value as sensitive
- fix bug: release-plz release fails when no "-o json" given as argument

### CODE REVIEW

**Comment by mbodmer** [comment]
Sorry, I have made a mess with git. Have now force pushed again and fixed the last clippy warning

**Comment by mbodmer** [comment]
Would you mind approving the builds? Or is there anything i can do?

**Comment by MarcoIeni** [comment]
Done! I'll review this asap

**Comment by MarcoIeni** [comment]
I extracted your fix in https://github.com/MarcoIeni/release-plz/pull/1528 because I wanted to merge it asap, thanks!

**Comment by mbodmer** [comment]
yes, the project Name is URL encoded, so 2%F is correct for the "/". Also you have to chose Maintainer role for the token.

**Comment by MarcoIeni** [comment]
I'll test again, thanks!
For the error, we could link to the docs if gitlab returns a 403

**Comment by mbodmer** [comment]
You seem to have a solution in mind, just go for it

**Review by MarcoIeni — APPROVED** [review]

**Pull request merged**
