### PR TITLE
fix: use token to fetch sparse metadata

### LINKED ISSUE #1415: Releasing to private registries fails due to token not being used
First, let me say a huge thanks for this amazing tool!

The release command takes a token, but that seems to only be used as an argument to `cargo publish`, but it should also be used to `fetch_sparse_metadata`, i.e. it should added as a request header.

Currently we get

```
  2024-04-25T11:03:24.583976Z ERROR  can't determine if package is published

Caused by:
    0: failed fetching sparse metadata
    1: the request was not authorized
```

### PR DESCRIPTION
**Pull request by hseeberger**
Fix #1415.

### CODE REVIEW

**Review by MarcoIeni — APPROVED** [review]

**Comment by MarcoIeni** [comment]
Thanks!

**Comment by hseeberger** [comment]
Thank you, @MarcoIeni, for merging quickly.
Any idea when you publish a new release?

**Comment by MarcoIeni** [comment]
today :)

**Comment by hseeberger** [comment]
Amazing!

**Pull request merged**
